### ISSUE TITLE
Github pages?

### ISSUE THREAD

**Issue by sylvia43** [ncase/coming-out-simulator-2014#1]
Rename `master` to `gh-pages`? Pretty please?

(it will create a Github page, hosting this project at `ncase.github.io/coming-out-simulator-2014`)

**Comment by sylvia43** [comment]
Also what happened with Nothing to Hide?

**Comment by ncase** [comment]
@anubiann00b Good plan, will make it a Github Page!

Also don't worry, this is just a side-project for the [Nar8 Game Jam](http://itch.io/jam/nar8-jam). Nothing To Hide is still going on, although I've been bad and haven't actually pushed code in a while. Recently on Nothing To Hide, I've been mostly doing writing, art, and other not-actually-code-stuff. 

...Also those backer rewards which I somehow _still_ haven't finished fulfilling. :(

**Comment by sylvia43** [comment]
Pls? I want to try it ^_^

**Comment by ncase** [comment]
@anubiann00b Done! Thanks again for the suggestion.
http://ncase.me/coming-out-simulator-2014/
